[2022-07-10 10:31:14 +0000] [9] [INFO] Starting gunicorn 20.1.0
[2022-07-10 10:31:14 +0000] [9] [INFO] Listening at: http://0.0.0.0:8001 (9)
[2022-07-10 10:31:14 +0000] [9] [INFO] Using worker: sync
[2022-07-10 10:31:14 +0000] [10] [INFO] Booting worker with pid: 10
[2022-07-10 10:31:14 +0000] [10] [ERROR] Exception in worker process
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/gunicorn/arbiter.py", line 589, in spawn_worker
    worker.init_process()
  File "/usr/local/lib/python3.9/site-packages/gunicorn/workers/base.py", line 134, in init_process
    self.load_wsgi()
  File "/usr/local/lib/python3.9/site-packages/gunicorn/workers/base.py", line 146, in load_wsgi
    self.wsgi = self.app.wsgi()
  File "/usr/local/lib/python3.9/site-packages/gunicorn/app/base.py", line 67, in wsgi
    self.callable = self.load()
  File "/usr/local/lib/python3.9/site-packages/gunicorn/app/wsgiapp.py", line 58, in load
    return self.load_wsgiapp()
  File "/usr/local/lib/python3.9/site-packages/gunicorn/app/wsgiapp.py", line 48, in load_wsgiapp
    return util.import_app(self.app_uri)
  File "/usr/local/lib/python3.9/site-packages/gunicorn/util.py", line 359, in import_app
    mod = importlib.import_module(module)
  File "/usr/local/lib/python3.9/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 680, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/opt/services/djangoapp/src/project/project/wsgi.py", line 16, in <module>
    application = get_wsgi_application()
  File "/usr/local/lib/python3.9/site-packages/django/core/wsgi.py", line 12, in get_wsgi_application
    django.setup(set_prefix=False)
  File "/usr/local/lib/python3.9/site-packages/django/__init__.py", line 24, in setup
    apps.populate(settings.INSTALLED_APPS)
  File "/usr/local/lib/python3.9/site-packages/django/apps/registry.py", line 91, in populate
    app_config = AppConfig.create(entry)
  File "/usr/local/lib/python3.9/site-packages/django/apps/config.py", line 223, in create
    import_module(entry)
  File "/usr/local/lib/python3.9/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 984, in _find_and_load_unlocked
ModuleNotFoundError: No module named 'core'
[2022-07-10 10:31:14 +0000] [10] [INFO] Worker exiting (pid: 10)
[2022-07-10 10:31:14 +0000] [9] [INFO] Shutting down: Master
[2022-07-10 10:31:14 +0000] [9] [INFO] Reason: Worker failed to boot.
[2022-07-10 10:31:15 +0000] [11] [INFO] Starting gunicorn 20.1.0
[2022-07-10 10:31:15 +0000] [11] [INFO] Listening at: http://0.0.0.0:8001 (11)
[2022-07-10 10:31:15 +0000] [11] [INFO] Using worker: sync
[2022-07-10 10:31:15 +0000] [12] [INFO] Booting worker with pid: 12
[2022-07-10 10:31:16 +0000] [12] [ERROR] Exception in worker process
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/gunicorn/arbiter.py", line 589, in spawn_worker
    worker.init_process()
  File "/usr/local/lib/python3.9/site-packages/gunicorn/workers/base.py", line 134, in init_process
    self.load_wsgi()
  File "/usr/local/lib/python3.9/site-packages/gunicorn/workers/base.py", line 146, in load_wsgi
    self.wsgi = self.app.wsgi()
  File "/usr/local/lib/python3.9/site-packages/gunicorn/app/base.py", line 67, in wsgi
    self.callable = self.load()
  File "/usr/local/lib/python3.9/site-packages/gunicorn/app/wsgiapp.py", line 58, in load
    return self.load_wsgiapp()
  File "/usr/local/lib/python3.9/site-packages/gunicorn/app/wsgiapp.py", line 48, in load_wsgiapp
    return util.import_app(self.app_uri)
  File "/usr/local/lib/python3.9/site-packages/gunicorn/util.py", line 359, in import_app
    mod = importlib.import_module(module)
  File "/usr/local/lib/python3.9/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 680, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/opt/services/djangoapp/src/project/project/wsgi.py", line 16, in <module>
    application = get_wsgi_application()
  File "/usr/local/lib/python3.9/site-packages/django/core/wsgi.py", line 12, in get_wsgi_application
    django.setup(set_prefix=False)
  File "/usr/local/lib/python3.9/site-packages/django/__init__.py", line 24, in setup
    apps.populate(settings.INSTALLED_APPS)
  File "/usr/local/lib/python3.9/site-packages/django/apps/registry.py", line 91, in populate
    app_config = AppConfig.create(entry)
  File "/usr/local/lib/python3.9/site-packages/django/apps/config.py", line 223, in create
    import_module(entry)
  File "/usr/local/lib/python3.9/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 984, in _find_and_load_unlocked
ModuleNotFoundError: No module named 'core'
[2022-07-10 10:31:16 +0000] [12] [INFO] Worker exiting (pid: 12)
[2022-07-10 10:31:16 +0000] [11] [INFO] Shutting down: Master
[2022-07-10 10:31:16 +0000] [11] [INFO] Reason: Worker failed to boot.
[2022-07-10 10:31:18 +0000] [13] [INFO] Starting gunicorn 20.1.0
[2022-07-10 10:31:18 +0000] [13] [INFO] Listening at: http://0.0.0.0:8001 (13)
[2022-07-10 10:31:18 +0000] [13] [INFO] Using worker: sync
[2022-07-10 10:31:18 +0000] [14] [INFO] Booting worker with pid: 14
[2022-07-10 10:31:18 +0000] [14] [ERROR] Exception in worker process
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/gunicorn/arbiter.py", line 589, in spawn_worker
    worker.init_process()
  File "/usr/local/lib/python3.9/site-packages/gunicorn/workers/base.py", line 134, in init_process
    self.load_wsgi()
  File "/usr/local/lib/python3.9/site-packages/gunicorn/workers/base.py", line 146, in load_wsgi
    self.wsgi = self.app.wsgi()
  File "/usr/local/lib/python3.9/site-packages/gunicorn/app/base.py", line 67, in wsgi
    self.callable = self.load()
  File "/usr/local/lib/python3.9/site-packages/gunicorn/app/wsgiapp.py", line 58, in load
    return self.load_wsgiapp()
  File "/usr/local/lib/python3.9/site-packages/gunicorn/app/wsgiapp.py", line 48, in load_wsgiapp
    return util.import_app(self.app_uri)
  File "/usr/local/lib/python3.9/site-packages/gunicorn/util.py", line 359, in import_app
    mod = importlib.import_module(module)
  File "/usr/local/lib/python3.9/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 680, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/opt/services/djangoapp/src/project/project/wsgi.py", line 16, in <module>
    application = get_wsgi_application()
  File "/usr/local/lib/python3.9/site-packages/django/core/wsgi.py", line 12, in get_wsgi_application
    django.setup(set_prefix=False)
  File "/usr/local/lib/python3.9/site-packages/django/__init__.py", line 24, in setup
    apps.populate(settings.INSTALLED_APPS)
  File "/usr/local/lib/python3.9/site-packages/django/apps/registry.py", line 91, in populate
    app_config = AppConfig.create(entry)
  File "/usr/local/lib/python3.9/site-packages/django/apps/config.py", line 223, in create
    import_module(entry)
  File "/usr/local/lib/python3.9/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 984, in _find_and_load_unlocked
ModuleNotFoundError: No module named 'core'
[2022-07-10 10:31:18 +0000] [14] [INFO] Worker exiting (pid: 14)
[2022-07-10 10:31:18 +0000] [13] [INFO] Shutting down: Master
[2022-07-10 10:31:18 +0000] [13] [INFO] Reason: Worker failed to boot.
[2022-07-10 10:31:21 +0000] [15] [INFO] Starting gunicorn 20.1.0
[2022-07-10 10:31:21 +0000] [15] [INFO] Listening at: http://0.0.0.0:8001 (15)
[2022-07-10 10:31:21 +0000] [15] [INFO] Using worker: sync
[2022-07-10 10:31:21 +0000] [16] [INFO] Booting worker with pid: 16
[2022-07-10 10:31:21 +0000] [16] [ERROR] Exception in worker process
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/gunicorn/arbiter.py", line 589, in spawn_worker
    worker.init_process()
  File "/usr/local/lib/python3.9/site-packages/gunicorn/workers/base.py", line 134, in init_process
    self.load_wsgi()
  File "/usr/local/lib/python3.9/site-packages/gunicorn/workers/base.py", line 146, in load_wsgi
    self.wsgi = self.app.wsgi()
  File "/usr/local/lib/python3.9/site-packages/gunicorn/app/base.py", line 67, in wsgi
    self.callable = self.load()
  File "/usr/local/lib/python3.9/site-packages/gunicorn/app/wsgiapp.py", line 58, in load
    return self.load_wsgiapp()
  File "/usr/local/lib/python3.9/site-packages/gunicorn/app/wsgiapp.py", line 48, in load_wsgiapp
    return util.import_app(self.app_uri)
  File "/usr/local/lib/python3.9/site-packages/gunicorn/util.py", line 359, in import_app
    mod = importlib.import_module(module)
  File "/usr/local/lib/python3.9/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 680, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/opt/services/djangoapp/src/project/project/wsgi.py", line 16, in <module>
    application = get_wsgi_application()
  File "/usr/local/lib/python3.9/site-packages/django/core/wsgi.py", line 12, in get_wsgi_application
    django.setup(set_prefix=False)
  File "/usr/local/lib/python3.9/site-packages/django/__init__.py", line 24, in setup
    apps.populate(settings.INSTALLED_APPS)
  File "/usr/local/lib/python3.9/site-packages/django/apps/registry.py", line 91, in populate
    app_config = AppConfig.create(entry)
  File "/usr/local/lib/python3.9/site-packages/django/apps/config.py", line 223, in create
    import_module(entry)
  File "/usr/local/lib/python3.9/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 984, in _find_and_load_unlocked
ModuleNotFoundError: No module named 'core'
[2022-07-10 10:31:21 +0000] [16] [INFO] Worker exiting (pid: 16)
[2022-07-10 10:31:21 +0000] [15] [INFO] Shutting down: Master
[2022-07-10 10:31:21 +0000] [15] [INFO] Reason: Worker failed to boot.
[2022-07-10 11:19:44 +0000] [8] [INFO] Starting gunicorn 20.1.0
[2022-07-10 11:19:44 +0000] [8] [INFO] Listening at: http://0.0.0.0:8001 (8)
[2022-07-10 11:19:44 +0000] [8] [INFO] Using worker: sync
[2022-07-10 11:19:44 +0000] [9] [INFO] Booting worker with pid: 9
[2022-07-10 11:19:44 +0000] [9] [ERROR] Exception in worker process
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/gunicorn/arbiter.py", line 589, in spawn_worker
    worker.init_process()
  File "/usr/local/lib/python3.9/site-packages/gunicorn/workers/base.py", line 134, in init_process
    self.load_wsgi()
  File "/usr/local/lib/python3.9/site-packages/gunicorn/workers/base.py", line 146, in load_wsgi
    self.wsgi = self.app.wsgi()
  File "/usr/local/lib/python3.9/site-packages/gunicorn/app/base.py", line 67, in wsgi
    self.callable = self.load()
  File "/usr/local/lib/python3.9/site-packages/gunicorn/app/wsgiapp.py", line 58, in load
    return self.load_wsgiapp()
  File "/usr/local/lib/python3.9/site-packages/gunicorn/app/wsgiapp.py", line 48, in load_wsgiapp
    return util.import_app(self.app_uri)
  File "/usr/local/lib/python3.9/site-packages/gunicorn/util.py", line 359, in import_app
    mod = importlib.import_module(module)
  File "/usr/local/lib/python3.9/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 680, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/opt/services/djangoapp/src/project/project/wsgi.py", line 16, in <module>
    application = get_wsgi_application()
  File "/usr/local/lib/python3.9/site-packages/django/core/wsgi.py", line 12, in get_wsgi_application
    django.setup(set_prefix=False)
  File "/usr/local/lib/python3.9/site-packages/django/__init__.py", line 24, in setup
    apps.populate(settings.INSTALLED_APPS)
  File "/usr/local/lib/python3.9/site-packages/django/apps/registry.py", line 91, in populate
    app_config = AppConfig.create(entry)
  File "/usr/local/lib/python3.9/site-packages/django/apps/config.py", line 223, in create
    import_module(entry)
  File "/usr/local/lib/python3.9/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 984, in _find_and_load_unlocked
ModuleNotFoundError: No module named 'core'
[2022-07-10 11:19:44 +0000] [9] [INFO] Worker exiting (pid: 9)
[2022-07-10 11:19:44 +0000] [8] [INFO] Shutting down: Master
[2022-07-10 11:19:44 +0000] [8] [INFO] Reason: Worker failed to boot.
[2022-07-10 11:19:45 +0000] [10] [INFO] Starting gunicorn 20.1.0
[2022-07-10 11:19:45 +0000] [10] [INFO] Listening at: http://0.0.0.0:8001 (10)
[2022-07-10 11:19:45 +0000] [10] [INFO] Using worker: sync
[2022-07-10 11:19:45 +0000] [11] [INFO] Booting worker with pid: 11
[2022-07-10 11:19:45 +0000] [11] [ERROR] Exception in worker process
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/gunicorn/arbiter.py", line 589, in spawn_worker
    worker.init_process()
  File "/usr/local/lib/python3.9/site-packages/gunicorn/workers/base.py", line 134, in init_process
    self.load_wsgi()
  File "/usr/local/lib/python3.9/site-packages/gunicorn/workers/base.py", line 146, in load_wsgi
    self.wsgi = self.app.wsgi()
  File "/usr/local/lib/python3.9/site-packages/gunicorn/app/base.py", line 67, in wsgi
    self.callable = self.load()
  File "/usr/local/lib/python3.9/site-packages/gunicorn/app/wsgiapp.py", line 58, in load
    return self.load_wsgiapp()
  File "/usr/local/lib/python3.9/site-packages/gunicorn/app/wsgiapp.py", line 48, in load_wsgiapp
    return util.import_app(self.app_uri)
  File "/usr/local/lib/python3.9/site-packages/gunicorn/util.py", line 359, in import_app
    mod = importlib.import_module(module)
  File "/usr/local/lib/python3.9/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 680, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/opt/services/djangoapp/src/project/project/wsgi.py", line 16, in <module>
    application = get_wsgi_application()
  File "/usr/local/lib/python3.9/site-packages/django/core/wsgi.py", line 12, in get_wsgi_application
    django.setup(set_prefix=False)
  File "/usr/local/lib/python3.9/site-packages/django/__init__.py", line 24, in setup
    apps.populate(settings.INSTALLED_APPS)
  File "/usr/local/lib/python3.9/site-packages/django/apps/registry.py", line 91, in populate
    app_config = AppConfig.create(entry)
  File "/usr/local/lib/python3.9/site-packages/django/apps/config.py", line 223, in create
    import_module(entry)
  File "/usr/local/lib/python3.9/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 984, in _find_and_load_unlocked
ModuleNotFoundError: No module named 'core'
[2022-07-10 11:19:45 +0000] [11] [INFO] Worker exiting (pid: 11)
[2022-07-10 11:19:45 +0000] [10] [INFO] Shutting down: Master
[2022-07-10 11:19:45 +0000] [10] [INFO] Reason: Worker failed to boot.
[2022-07-10 11:19:48 +0000] [12] [INFO] Starting gunicorn 20.1.0
[2022-07-10 11:19:48 +0000] [12] [INFO] Listening at: http://0.0.0.0:8001 (12)
[2022-07-10 11:19:48 +0000] [12] [INFO] Using worker: sync
[2022-07-10 11:19:48 +0000] [13] [INFO] Booting worker with pid: 13
[2022-07-10 11:19:48 +0000] [13] [ERROR] Exception in worker process
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/gunicorn/arbiter.py", line 589, in spawn_worker
    worker.init_process()
  File "/usr/local/lib/python3.9/site-packages/gunicorn/workers/base.py", line 134, in init_process
    self.load_wsgi()
  File "/usr/local/lib/python3.9/site-packages/gunicorn/workers/base.py", line 146, in load_wsgi
    self.wsgi = self.app.wsgi()
  File "/usr/local/lib/python3.9/site-packages/gunicorn/app/base.py", line 67, in wsgi
    self.callable = self.load()
  File "/usr/local/lib/python3.9/site-packages/gunicorn/app/wsgiapp.py", line 58, in load
    return self.load_wsgiapp()
  File "/usr/local/lib/python3.9/site-packages/gunicorn/app/wsgiapp.py", line 48, in load_wsgiapp
    return util.import_app(self.app_uri)
  File "/usr/local/lib/python3.9/site-packages/gunicorn/util.py", line 359, in import_app
    mod = importlib.import_module(module)
  File "/usr/local/lib/python3.9/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 680, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/opt/services/djangoapp/src/project/project/wsgi.py", line 16, in <module>
    application = get_wsgi_application()
  File "/usr/local/lib/python3.9/site-packages/django/core/wsgi.py", line 12, in get_wsgi_application
    django.setup(set_prefix=False)
  File "/usr/local/lib/python3.9/site-packages/django/__init__.py", line 24, in setup
    apps.populate(settings.INSTALLED_APPS)
  File "/usr/local/lib/python3.9/site-packages/django/apps/registry.py", line 91, in populate
    app_config = AppConfig.create(entry)
  File "/usr/local/lib/python3.9/site-packages/django/apps/config.py", line 223, in create
    import_module(entry)
  File "/usr/local/lib/python3.9/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 984, in _find_and_load_unlocked
ModuleNotFoundError: No module named 'core'
[2022-07-10 11:19:48 +0000] [13] [INFO] Worker exiting (pid: 13)
[2022-07-10 11:19:48 +0000] [12] [INFO] Shutting down: Master
[2022-07-10 11:19:48 +0000] [12] [INFO] Reason: Worker failed to boot.
[2022-07-10 11:19:51 +0000] [14] [INFO] Starting gunicorn 20.1.0
[2022-07-10 11:19:51 +0000] [14] [INFO] Listening at: http://0.0.0.0:8001 (14)
[2022-07-10 11:19:51 +0000] [14] [INFO] Using worker: sync
[2022-07-10 11:19:51 +0000] [15] [INFO] Booting worker with pid: 15
[2022-07-10 11:19:51 +0000] [15] [ERROR] Exception in worker process
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/gunicorn/arbiter.py", line 589, in spawn_worker
    worker.init_process()
  File "/usr/local/lib/python3.9/site-packages/gunicorn/workers/base.py", line 134, in init_process
    self.load_wsgi()
  File "/usr/local/lib/python3.9/site-packages/gunicorn/workers/base.py", line 146, in load_wsgi
    self.wsgi = self.app.wsgi()
  File "/usr/local/lib/python3.9/site-packages/gunicorn/app/base.py", line 67, in wsgi
    self.callable = self.load()
  File "/usr/local/lib/python3.9/site-packages/gunicorn/app/wsgiapp.py", line 58, in load
    return self.load_wsgiapp()
  File "/usr/local/lib/python3.9/site-packages/gunicorn/app/wsgiapp.py", line 48, in load_wsgiapp
    return util.import_app(self.app_uri)
  File "/usr/local/lib/python3.9/site-packages/gunicorn/util.py", line 359, in import_app
    mod = importlib.import_module(module)
  File "/usr/local/lib/python3.9/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 680, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/opt/services/djangoapp/src/project/project/wsgi.py", line 16, in <module>
    application = get_wsgi_application()
  File "/usr/local/lib/python3.9/site-packages/django/core/wsgi.py", line 12, in get_wsgi_application
    django.setup(set_prefix=False)
  File "/usr/local/lib/python3.9/site-packages/django/__init__.py", line 24, in setup
    apps.populate(settings.INSTALLED_APPS)
  File "/usr/local/lib/python3.9/site-packages/django/apps/registry.py", line 91, in populate
    app_config = AppConfig.create(entry)
  File "/usr/local/lib/python3.9/site-packages/django/apps/config.py", line 223, in create
    import_module(entry)
  File "/usr/local/lib/python3.9/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 984, in _find_and_load_unlocked
ModuleNotFoundError: No module named 'core'
[2022-07-10 11:19:51 +0000] [15] [INFO] Worker exiting (pid: 15)
[2022-07-10 11:19:51 +0000] [14] [INFO] Shutting down: Master
[2022-07-10 11:19:51 +0000] [14] [INFO] Reason: Worker failed to boot.
[2022-07-10 11:49:46 +0000] [9] [INFO] Starting gunicorn 20.1.0
[2022-07-10 11:49:46 +0000] [9] [INFO] Listening at: http://0.0.0.0:8001 (9)
[2022-07-10 11:49:46 +0000] [9] [INFO] Using worker: sync
[2022-07-10 11:49:46 +0000] [10] [INFO] Booting worker with pid: 10
[2022-07-10 11:49:47 +0000] [10] [ERROR] Exception in worker process
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/gunicorn/arbiter.py", line 589, in spawn_worker
    worker.init_process()
  File "/usr/local/lib/python3.9/site-packages/gunicorn/workers/base.py", line 134, in init_process
    self.load_wsgi()
  File "/usr/local/lib/python3.9/site-packages/gunicorn/workers/base.py", line 146, in load_wsgi
    self.wsgi = self.app.wsgi()
  File "/usr/local/lib/python3.9/site-packages/gunicorn/app/base.py", line 67, in wsgi
    self.callable = self.load()
  File "/usr/local/lib/python3.9/site-packages/gunicorn/app/wsgiapp.py", line 58, in load
    return self.load_wsgiapp()
  File "/usr/local/lib/python3.9/site-packages/gunicorn/app/wsgiapp.py", line 48, in load_wsgiapp
    return util.import_app(self.app_uri)
  File "/usr/local/lib/python3.9/site-packages/gunicorn/util.py", line 359, in import_app
    mod = importlib.import_module(module)
  File "/usr/local/lib/python3.9/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 680, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/opt/services/djangoapp/src/project/project/wsgi.py", line 16, in <module>
    application = get_wsgi_application()
  File "/usr/local/lib/python3.9/site-packages/django/core/wsgi.py", line 12, in get_wsgi_application
    django.setup(set_prefix=False)
  File "/usr/local/lib/python3.9/site-packages/django/__init__.py", line 24, in setup
    apps.populate(settings.INSTALLED_APPS)
  File "/usr/local/lib/python3.9/site-packages/django/apps/registry.py", line 122, in populate
    app_config.ready()
  File "/opt/services/djangoapp/src/project/core/apps.py", line 8, in ready
    import core.PushNotification
  File "/opt/services/djangoapp/src/project/core/PushNotification.py", line 1, in <module>
    from push_notifications.models import APNSDevice, GCMDevice
  File "/usr/local/lib/python3.9/site-packages/push_notifications/models.py", line 2, in <module>
    from django.utils.translation import ugettext_lazy as _
ImportError: cannot import name 'ugettext_lazy' from 'django.utils.translation' (/usr/local/lib/python3.9/site-packages/django/utils/translation/__init__.py)
[2022-07-10 11:49:47 +0000] [10] [INFO] Worker exiting (pid: 10)
[2022-07-10 11:49:47 +0000] [9] [INFO] Shutting down: Master
[2022-07-10 11:49:47 +0000] [9] [INFO] Reason: Worker failed to boot.
[2022-07-10 11:49:48 +0000] [13] [INFO] Starting gunicorn 20.1.0
[2022-07-10 11:49:48 +0000] [13] [INFO] Listening at: http://0.0.0.0:8001 (13)
[2022-07-10 11:49:48 +0000] [13] [INFO] Using worker: sync
[2022-07-10 11:49:48 +0000] [14] [INFO] Booting worker with pid: 14
[2022-07-10 11:49:48 +0000] [14] [ERROR] Exception in worker process
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/gunicorn/arbiter.py", line 589, in spawn_worker
    worker.init_process()
  File "/usr/local/lib/python3.9/site-packages/gunicorn/workers/base.py", line 134, in init_process
    self.load_wsgi()
  File "/usr/local/lib/python3.9/site-packages/gunicorn/workers/base.py", line 146, in load_wsgi
    self.wsgi = self.app.wsgi()
  File "/usr/local/lib/python3.9/site-packages/gunicorn/app/base.py", line 67, in wsgi
    self.callable = self.load()
  File "/usr/local/lib/python3.9/site-packages/gunicorn/app/wsgiapp.py", line 58, in load
    return self.load_wsgiapp()
  File "/usr/local/lib/python3.9/site-packages/gunicorn/app/wsgiapp.py", line 48, in load_wsgiapp
    return util.import_app(self.app_uri)
  File "/usr/local/lib/python3.9/site-packages/gunicorn/util.py", line 359, in import_app
    mod = importlib.import_module(module)
  File "/usr/local/lib/python3.9/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 680, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/opt/services/djangoapp/src/project/project/wsgi.py", line 16, in <module>
    application = get_wsgi_application()
  File "/usr/local/lib/python3.9/site-packages/django/core/wsgi.py", line 12, in get_wsgi_application
    django.setup(set_prefix=False)
  File "/usr/local/lib/python3.9/site-packages/django/__init__.py", line 24, in setup
    apps.populate(settings.INSTALLED_APPS)
  File "/usr/local/lib/python3.9/site-packages/django/apps/registry.py", line 122, in populate
    app_config.ready()
  File "/opt/services/djangoapp/src/project/core/apps.py", line 8, in ready
    import core.PushNotification
  File "/opt/services/djangoapp/src/project/core/PushNotification.py", line 1, in <module>
    from push_notifications.models import APNSDevice, GCMDevice
  File "/usr/local/lib/python3.9/site-packages/push_notifications/models.py", line 2, in <module>
    from django.utils.translation import ugettext_lazy as _
ImportError: cannot import name 'ugettext_lazy' from 'django.utils.translation' (/usr/local/lib/python3.9/site-packages/django/utils/translation/__init__.py)
[2022-07-10 11:49:48 +0000] [14] [INFO] Worker exiting (pid: 14)
[2022-07-10 11:49:48 +0000] [13] [INFO] Shutting down: Master
[2022-07-10 11:49:48 +0000] [13] [INFO] Reason: Worker failed to boot.
[2022-07-10 11:49:50 +0000] [17] [INFO] Starting gunicorn 20.1.0
[2022-07-10 11:49:50 +0000] [17] [INFO] Listening at: http://0.0.0.0:8001 (17)
[2022-07-10 11:49:50 +0000] [17] [INFO] Using worker: sync
[2022-07-10 11:49:50 +0000] [18] [INFO] Booting worker with pid: 18
[2022-07-10 11:49:51 +0000] [18] [ERROR] Exception in worker process
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/gunicorn/arbiter.py", line 589, in spawn_worker
    worker.init_process()
  File "/usr/local/lib/python3.9/site-packages/gunicorn/workers/base.py", line 134, in init_process
    self.load_wsgi()
  File "/usr/local/lib/python3.9/site-packages/gunicorn/workers/base.py", line 146, in load_wsgi
    self.wsgi = self.app.wsgi()
  File "/usr/local/lib/python3.9/site-packages/gunicorn/app/base.py", line 67, in wsgi
    self.callable = self.load()
  File "/usr/local/lib/python3.9/site-packages/gunicorn/app/wsgiapp.py", line 58, in load
    return self.load_wsgiapp()
  File "/usr/local/lib/python3.9/site-packages/gunicorn/app/wsgiapp.py", line 48, in load_wsgiapp
    return util.import_app(self.app_uri)
  File "/usr/local/lib/python3.9/site-packages/gunicorn/util.py", line 359, in import_app
    mod = importlib.import_module(module)
  File "/usr/local/lib/python3.9/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 680, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/opt/services/djangoapp/src/project/project/wsgi.py", line 16, in <module>
    application = get_wsgi_application()
  File "/usr/local/lib/python3.9/site-packages/django/core/wsgi.py", line 12, in get_wsgi_application
    django.setup(set_prefix=False)
  File "/usr/local/lib/python3.9/site-packages/django/__init__.py", line 24, in setup
    apps.populate(settings.INSTALLED_APPS)
  File "/usr/local/lib/python3.9/site-packages/django/apps/registry.py", line 122, in populate
    app_config.ready()
  File "/opt/services/djangoapp/src/project/core/apps.py", line 8, in ready
    import core.PushNotification
  File "/opt/services/djangoapp/src/project/core/PushNotification.py", line 1, in <module>
    from push_notifications.models import APNSDevice, GCMDevice
  File "/usr/local/lib/python3.9/site-packages/push_notifications/models.py", line 2, in <module>
    from django.utils.translation import ugettext_lazy as _
ImportError: cannot import name 'ugettext_lazy' from 'django.utils.translation' (/usr/local/lib/python3.9/site-packages/django/utils/translation/__init__.py)
[2022-07-10 11:49:51 +0000] [18] [INFO] Worker exiting (pid: 18)
[2022-07-10 11:49:51 +0000] [17] [INFO] Shutting down: Master
[2022-07-10 11:49:51 +0000] [17] [INFO] Reason: Worker failed to boot.
[2022-07-10 11:49:54 +0000] [21] [INFO] Starting gunicorn 20.1.0
[2022-07-10 11:49:54 +0000] [21] [INFO] Listening at: http://0.0.0.0:8001 (21)
[2022-07-10 11:49:54 +0000] [21] [INFO] Using worker: sync
[2022-07-10 11:49:54 +0000] [22] [INFO] Booting worker with pid: 22
[2022-07-10 11:49:54 +0000] [22] [ERROR] Exception in worker process
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/gunicorn/arbiter.py", line 589, in spawn_worker
    worker.init_process()
  File "/usr/local/lib/python3.9/site-packages/gunicorn/workers/base.py", line 134, in init_process
    self.load_wsgi()
  File "/usr/local/lib/python3.9/site-packages/gunicorn/workers/base.py", line 146, in load_wsgi
    self.wsgi = self.app.wsgi()
  File "/usr/local/lib/python3.9/site-packages/gunicorn/app/base.py", line 67, in wsgi
    self.callable = self.load()
  File "/usr/local/lib/python3.9/site-packages/gunicorn/app/wsgiapp.py", line 58, in load
    return self.load_wsgiapp()
  File "/usr/local/lib/python3.9/site-packages/gunicorn/app/wsgiapp.py", line 48, in load_wsgiapp
    return util.import_app(self.app_uri)
  File "/usr/local/lib/python3.9/site-packages/gunicorn/util.py", line 359, in import_app
    mod = importlib.import_module(module)
  File "/usr/local/lib/python3.9/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 680, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/opt/services/djangoapp/src/project/project/wsgi.py", line 16, in <module>
    application = get_wsgi_application()
  File "/usr/local/lib/python3.9/site-packages/django/core/wsgi.py", line 12, in get_wsgi_application
    django.setup(set_prefix=False)
  File "/usr/local/lib/python3.9/site-packages/django/__init__.py", line 24, in setup
    apps.populate(settings.INSTALLED_APPS)
  File "/usr/local/lib/python3.9/site-packages/django/apps/registry.py", line 122, in populate
    app_config.ready()
  File "/opt/services/djangoapp/src/project/core/apps.py", line 8, in ready
    import core.PushNotification
  File "/opt/services/djangoapp/src/project/core/PushNotification.py", line 1, in <module>
    from push_notifications.models import APNSDevice, GCMDevice
  File "/usr/local/lib/python3.9/site-packages/push_notifications/models.py", line 2, in <module>
    from django.utils.translation import ugettext_lazy as _
ImportError: cannot import name 'ugettext_lazy' from 'django.utils.translation' (/usr/local/lib/python3.9/site-packages/django/utils/translation/__init__.py)
[2022-07-10 11:49:54 +0000] [22] [INFO] Worker exiting (pid: 22)
[2022-07-10 11:49:54 +0000] [21] [INFO] Shutting down: Master
[2022-07-10 11:49:54 +0000] [21] [INFO] Reason: Worker failed to boot.
[2022-07-10 12:03:12 +0000] [8] [INFO] Starting gunicorn 20.1.0
[2022-07-10 12:03:12 +0000] [8] [INFO] Listening at: http://0.0.0.0:8001 (8)
[2022-07-10 12:03:12 +0000] [8] [INFO] Using worker: sync
[2022-07-10 12:03:12 +0000] [9] [INFO] Booting worker with pid: 9
[2022-07-10 12:03:13 +0000] [9] [ERROR] Exception in worker process
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/gunicorn/arbiter.py", line 589, in spawn_worker
    worker.init_process()
  File "/usr/local/lib/python3.9/site-packages/gunicorn/workers/base.py", line 134, in init_process
    self.load_wsgi()
  File "/usr/local/lib/python3.9/site-packages/gunicorn/workers/base.py", line 146, in load_wsgi
    self.wsgi = self.app.wsgi()
  File "/usr/local/lib/python3.9/site-packages/gunicorn/app/base.py", line 67, in wsgi
    self.callable = self.load()
  File "/usr/local/lib/python3.9/site-packages/gunicorn/app/wsgiapp.py", line 58, in load
    return self.load_wsgiapp()
  File "/usr/local/lib/python3.9/site-packages/gunicorn/app/wsgiapp.py", line 48, in load_wsgiapp
    return util.import_app(self.app_uri)
  File "/usr/local/lib/python3.9/site-packages/gunicorn/util.py", line 359, in import_app
    mod = importlib.import_module(module)
  File "/usr/local/lib/python3.9/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 680, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/opt/services/djangoapp/src/project/project/wsgi.py", line 16, in <module>
    application = get_wsgi_application()
  File "/usr/local/lib/python3.9/site-packages/django/core/wsgi.py", line 12, in get_wsgi_application
    django.setup(set_prefix=False)
  File "/usr/local/lib/python3.9/site-packages/django/__init__.py", line 24, in setup
    apps.populate(settings.INSTALLED_APPS)
  File "/usr/local/lib/python3.9/site-packages/django/apps/registry.py", line 124, in populate
    app_config.ready()
  File "/opt/services/djangoapp/src/project/core/apps.py", line 8, in ready
    import core.PushNotification
  File "/opt/services/djangoapp/src/project/core/PushNotification.py", line 1, in <module>
    from push_notifications.models import APNSDevice, GCMDevice
  File "/usr/local/lib/python3.9/site-packages/push_notifications/models.py", line 86, in <module>
    class GCMDevice(Device):
  File "/usr/local/lib/python3.9/site-packages/django/db/models/base.py", line 132, in __new__
    raise RuntimeError(
RuntimeError: Model class push_notifications.models.GCMDevice doesn't declare an explicit app_label and isn't in an application in INSTALLED_APPS.
[2022-07-10 12:03:13 +0000] [9] [INFO] Worker exiting (pid: 9)
[2022-07-10 12:03:13 +0000] [8] [INFO] Shutting down: Master
[2022-07-10 12:03:13 +0000] [8] [INFO] Reason: Worker failed to boot.
[2022-07-10 12:03:14 +0000] [12] [INFO] Starting gunicorn 20.1.0
[2022-07-10 12:03:14 +0000] [12] [INFO] Listening at: http://0.0.0.0:8001 (12)
[2022-07-10 12:03:14 +0000] [12] [INFO] Using worker: sync
[2022-07-10 12:03:14 +0000] [13] [INFO] Booting worker with pid: 13
[2022-07-10 12:03:14 +0000] [13] [ERROR] Exception in worker process
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/gunicorn/arbiter.py", line 589, in spawn_worker
    worker.init_process()
  File "/usr/local/lib/python3.9/site-packages/gunicorn/workers/base.py", line 134, in init_process
    self.load_wsgi()
  File "/usr/local/lib/python3.9/site-packages/gunicorn/workers/base.py", line 146, in load_wsgi
    self.wsgi = self.app.wsgi()
  File "/usr/local/lib/python3.9/site-packages/gunicorn/app/base.py", line 67, in wsgi
    self.callable = self.load()
  File "/usr/local/lib/python3.9/site-packages/gunicorn/app/wsgiapp.py", line 58, in load
    return self.load_wsgiapp()
  File "/usr/local/lib/python3.9/site-packages/gunicorn/app/wsgiapp.py", line 48, in load_wsgiapp
    return util.import_app(self.app_uri)
  File "/usr/local/lib/python3.9/site-packages/gunicorn/util.py", line 359, in import_app
    mod = importlib.import_module(module)
  File "/usr/local/lib/python3.9/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 680, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/opt/services/djangoapp/src/project/project/wsgi.py", line 16, in <module>
    application = get_wsgi_application()
  File "/usr/local/lib/python3.9/site-packages/django/core/wsgi.py", line 12, in get_wsgi_application
    django.setup(set_prefix=False)
  File "/usr/local/lib/python3.9/site-packages/django/__init__.py", line 24, in setup
    apps.populate(settings.INSTALLED_APPS)
  File "/usr/local/lib/python3.9/site-packages/django/apps/registry.py", line 124, in populate
    app_config.ready()
  File "/opt/services/djangoapp/src/project/core/apps.py", line 8, in ready
    import core.PushNotification
  File "/opt/services/djangoapp/src/project/core/PushNotification.py", line 1, in <module>
    from push_notifications.models import APNSDevice, GCMDevice
  File "/usr/local/lib/python3.9/site-packages/push_notifications/models.py", line 86, in <module>
    class GCMDevice(Device):
  File "/usr/local/lib/python3.9/site-packages/django/db/models/base.py", line 132, in __new__
    raise RuntimeError(
RuntimeError: Model class push_notifications.models.GCMDevice doesn't declare an explicit app_label and isn't in an application in INSTALLED_APPS.
[2022-07-10 12:03:14 +0000] [13] [INFO] Worker exiting (pid: 13)
[2022-07-10 12:03:14 +0000] [12] [INFO] Shutting down: Master
[2022-07-10 12:03:14 +0000] [12] [INFO] Reason: Worker failed to boot.
[2022-07-10 12:03:16 +0000] [16] [INFO] Starting gunicorn 20.1.0
[2022-07-10 12:03:16 +0000] [16] [INFO] Listening at: http://0.0.0.0:8001 (16)
[2022-07-10 12:03:16 +0000] [16] [INFO] Using worker: sync
[2022-07-10 12:03:16 +0000] [17] [INFO] Booting worker with pid: 17
[2022-07-10 12:03:17 +0000] [17] [ERROR] Exception in worker process
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/gunicorn/arbiter.py", line 589, in spawn_worker
    worker.init_process()
  File "/usr/local/lib/python3.9/site-packages/gunicorn/workers/base.py", line 134, in init_process
    self.load_wsgi()
  File "/usr/local/lib/python3.9/site-packages/gunicorn/workers/base.py", line 146, in load_wsgi
    self.wsgi = self.app.wsgi()
  File "/usr/local/lib/python3.9/site-packages/gunicorn/app/base.py", line 67, in wsgi
    self.callable = self.load()
  File "/usr/local/lib/python3.9/site-packages/gunicorn/app/wsgiapp.py", line 58, in load
    return self.load_wsgiapp()
  File "/usr/local/lib/python3.9/site-packages/gunicorn/app/wsgiapp.py", line 48, in load_wsgiapp
    return util.import_app(self.app_uri)
  File "/usr/local/lib/python3.9/site-packages/gunicorn/util.py", line 359, in import_app
    mod = importlib.import_module(module)
  File "/usr/local/lib/python3.9/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 680, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/opt/services/djangoapp/src/project/project/wsgi.py", line 16, in <module>
    application = get_wsgi_application()
  File "/usr/local/lib/python3.9/site-packages/django/core/wsgi.py", line 12, in get_wsgi_application
    django.setup(set_prefix=False)
  File "/usr/local/lib/python3.9/site-packages/django/__init__.py", line 24, in setup
    apps.populate(settings.INSTALLED_APPS)
  File "/usr/local/lib/python3.9/site-packages/django/apps/registry.py", line 124, in populate
    app_config.ready()
  File "/opt/services/djangoapp/src/project/core/apps.py", line 8, in ready
    import core.PushNotification
  File "/opt/services/djangoapp/src/project/core/PushNotification.py", line 1, in <module>
    from push_notifications.models import APNSDevice, GCMDevice
  File "/usr/local/lib/python3.9/site-packages/push_notifications/models.py", line 86, in <module>
    class GCMDevice(Device):
  File "/usr/local/lib/python3.9/site-packages/django/db/models/base.py", line 132, in __new__
    raise RuntimeError(
RuntimeError: Model class push_notifications.models.GCMDevice doesn't declare an explicit app_label and isn't in an application in INSTALLED_APPS.
[2022-07-10 12:03:17 +0000] [17] [INFO] Worker exiting (pid: 17)
[2022-07-10 12:03:17 +0000] [16] [INFO] Shutting down: Master
[2022-07-10 12:03:17 +0000] [16] [INFO] Reason: Worker failed to boot.
[2022-07-10 12:03:20 +0000] [20] [INFO] Starting gunicorn 20.1.0
[2022-07-10 12:03:20 +0000] [20] [INFO] Listening at: http://0.0.0.0:8001 (20)
[2022-07-10 12:03:20 +0000] [20] [INFO] Using worker: sync
[2022-07-10 12:03:20 +0000] [21] [INFO] Booting worker with pid: 21
[2022-07-10 12:03:20 +0000] [21] [ERROR] Exception in worker process
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/gunicorn/arbiter.py", line 589, in spawn_worker
    worker.init_process()
  File "/usr/local/lib/python3.9/site-packages/gunicorn/workers/base.py", line 134, in init_process
    self.load_wsgi()
  File "/usr/local/lib/python3.9/site-packages/gunicorn/workers/base.py", line 146, in load_wsgi
    self.wsgi = self.app.wsgi()
  File "/usr/local/lib/python3.9/site-packages/gunicorn/app/base.py", line 67, in wsgi
    self.callable = self.load()
  File "/usr/local/lib/python3.9/site-packages/gunicorn/app/wsgiapp.py", line 58, in load
    return self.load_wsgiapp()
  File "/usr/local/lib/python3.9/site-packages/gunicorn/app/wsgiapp.py", line 48, in load_wsgiapp
    return util.import_app(self.app_uri)
  File "/usr/local/lib/python3.9/site-packages/gunicorn/util.py", line 359, in import_app
    mod = importlib.import_module(module)
  File "/usr/local/lib/python3.9/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 680, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/opt/services/djangoapp/src/project/project/wsgi.py", line 16, in <module>
    application = get_wsgi_application()
  File "/usr/local/lib/python3.9/site-packages/django/core/wsgi.py", line 12, in get_wsgi_application
    django.setup(set_prefix=False)
  File "/usr/local/lib/python3.9/site-packages/django/__init__.py", line 24, in setup
    apps.populate(settings.INSTALLED_APPS)
  File "/usr/local/lib/python3.9/site-packages/django/apps/registry.py", line 124, in populate
    app_config.ready()
  File "/opt/services/djangoapp/src/project/core/apps.py", line 8, in ready
    import core.PushNotification
  File "/opt/services/djangoapp/src/project/core/PushNotification.py", line 1, in <module>
    from push_notifications.models import APNSDevice, GCMDevice
  File "/usr/local/lib/python3.9/site-packages/push_notifications/models.py", line 86, in <module>
    class GCMDevice(Device):
  File "/usr/local/lib/python3.9/site-packages/django/db/models/base.py", line 132, in __new__
    raise RuntimeError(
RuntimeError: Model class push_notifications.models.GCMDevice doesn't declare an explicit app_label and isn't in an application in INSTALLED_APPS.
[2022-07-10 12:03:20 +0000] [21] [INFO] Worker exiting (pid: 21)
[2022-07-10 12:03:20 +0000] [20] [INFO] Shutting down: Master
[2022-07-10 12:03:20 +0000] [20] [INFO] Reason: Worker failed to boot.
[2022-07-10 12:09:21 +0000] [8] [INFO] Starting gunicorn 20.1.0
[2022-07-10 12:09:21 +0000] [8] [INFO] Listening at: http://0.0.0.0:8001 (8)
[2022-07-10 12:09:21 +0000] [8] [INFO] Using worker: sync
[2022-07-10 12:09:21 +0000] [9] [INFO] Booting worker with pid: 9
[2022-07-11 16:57:17 +0000] [8] [INFO] Handling signal: term
[2022-07-11 16:57:17 +0000] [9] [INFO] Worker exiting (pid: 9)
[2022-07-11 16:57:17 +0000] [8] [INFO] Shutting down: Master
[2022-07-11 16:57:30 +0000] [9] [INFO] Starting gunicorn 20.1.0
[2022-07-11 16:57:30 +0000] [9] [INFO] Listening at: http://0.0.0.0:8001 (9)
[2022-07-11 16:57:30 +0000] [9] [INFO] Using worker: sync
[2022-07-11 16:57:30 +0000] [10] [INFO] Booting worker with pid: 10
[2022-07-11 16:57:31 +0000] [10] [ERROR] Exception in worker process
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/gunicorn/arbiter.py", line 589, in spawn_worker
    worker.init_process()
  File "/usr/local/lib/python3.9/site-packages/gunicorn/workers/base.py", line 134, in init_process
    self.load_wsgi()
  File "/usr/local/lib/python3.9/site-packages/gunicorn/workers/base.py", line 146, in load_wsgi
    self.wsgi = self.app.wsgi()
  File "/usr/local/lib/python3.9/site-packages/gunicorn/app/base.py", line 67, in wsgi
    self.callable = self.load()
  File "/usr/local/lib/python3.9/site-packages/gunicorn/app/wsgiapp.py", line 58, in load
    return self.load_wsgiapp()
  File "/usr/local/lib/python3.9/site-packages/gunicorn/app/wsgiapp.py", line 48, in load_wsgiapp
    return util.import_app(self.app_uri)
  File "/usr/local/lib/python3.9/site-packages/gunicorn/util.py", line 359, in import_app
    mod = importlib.import_module(module)
  File "/usr/local/lib/python3.9/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 680, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/opt/services/djangoapp/src/project/project/wsgi.py", line 16, in <module>
    application = get_wsgi_application()
  File "/usr/local/lib/python3.9/site-packages/django/core/wsgi.py", line 12, in get_wsgi_application
    django.setup(set_prefix=False)
  File "/usr/local/lib/python3.9/site-packages/django/__init__.py", line 24, in setup
    apps.populate(settings.INSTALLED_APPS)
  File "/usr/local/lib/python3.9/site-packages/django/apps/registry.py", line 91, in populate
    app_config = AppConfig.create(entry)
  File "/usr/local/lib/python3.9/site-packages/django/apps/config.py", line 228, in create
    import_module(entry)
  File "/usr/local/lib/python3.9/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 984, in _find_and_load_unlocked
ModuleNotFoundError: No module named 'activity'
[2022-07-11 16:57:31 +0000] [10] [INFO] Worker exiting (pid: 10)
[2022-07-11 16:57:31 +0000] [9] [INFO] Shutting down: Master
[2022-07-11 16:57:31 +0000] [9] [INFO] Reason: Worker failed to boot.
[2022-07-11 16:57:32 +0000] [11] [INFO] Starting gunicorn 20.1.0
[2022-07-11 16:57:32 +0000] [11] [INFO] Listening at: http://0.0.0.0:8001 (11)
[2022-07-11 16:57:32 +0000] [11] [INFO] Using worker: sync
[2022-07-11 16:57:32 +0000] [12] [INFO] Booting worker with pid: 12
[2022-07-11 16:57:32 +0000] [12] [ERROR] Exception in worker process
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/gunicorn/arbiter.py", line 589, in spawn_worker
    worker.init_process()
  File "/usr/local/lib/python3.9/site-packages/gunicorn/workers/base.py", line 134, in init_process
    self.load_wsgi()
  File "/usr/local/lib/python3.9/site-packages/gunicorn/workers/base.py", line 146, in load_wsgi
    self.wsgi = self.app.wsgi()
  File "/usr/local/lib/python3.9/site-packages/gunicorn/app/base.py", line 67, in wsgi
    self.callable = self.load()
  File "/usr/local/lib/python3.9/site-packages/gunicorn/app/wsgiapp.py", line 58, in load
    return self.load_wsgiapp()
  File "/usr/local/lib/python3.9/site-packages/gunicorn/app/wsgiapp.py", line 48, in load_wsgiapp
    return util.import_app(self.app_uri)
  File "/usr/local/lib/python3.9/site-packages/gunicorn/util.py", line 359, in import_app
    mod = importlib.import_module(module)
  File "/usr/local/lib/python3.9/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 680, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/opt/services/djangoapp/src/project/project/wsgi.py", line 16, in <module>
    application = get_wsgi_application()
  File "/usr/local/lib/python3.9/site-packages/django/core/wsgi.py", line 12, in get_wsgi_application
    django.setup(set_prefix=False)
  File "/usr/local/lib/python3.9/site-packages/django/__init__.py", line 24, in setup
    apps.populate(settings.INSTALLED_APPS)
  File "/usr/local/lib/python3.9/site-packages/django/apps/registry.py", line 91, in populate
    app_config = AppConfig.create(entry)
  File "/usr/local/lib/python3.9/site-packages/django/apps/config.py", line 228, in create
    import_module(entry)
  File "/usr/local/lib/python3.9/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 984, in _find_and_load_unlocked
ModuleNotFoundError: No module named 'activity'
[2022-07-11 16:57:32 +0000] [12] [INFO] Worker exiting (pid: 12)
[2022-07-11 16:57:32 +0000] [11] [INFO] Shutting down: Master
[2022-07-11 16:57:32 +0000] [11] [INFO] Reason: Worker failed to boot.
[2022-07-11 16:57:34 +0000] [13] [INFO] Starting gunicorn 20.1.0
[2022-07-11 16:57:34 +0000] [13] [INFO] Listening at: http://0.0.0.0:8001 (13)
[2022-07-11 16:57:34 +0000] [13] [INFO] Using worker: sync
[2022-07-11 16:57:34 +0000] [14] [INFO] Booting worker with pid: 14
[2022-07-11 16:57:34 +0000] [14] [ERROR] Exception in worker process
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/gunicorn/arbiter.py", line 589, in spawn_worker
    worker.init_process()
  File "/usr/local/lib/python3.9/site-packages/gunicorn/workers/base.py", line 134, in init_process
    self.load_wsgi()
  File "/usr/local/lib/python3.9/site-packages/gunicorn/workers/base.py", line 146, in load_wsgi
    self.wsgi = self.app.wsgi()
  File "/usr/local/lib/python3.9/site-packages/gunicorn/app/base.py", line 67, in wsgi
    self.callable = self.load()
  File "/usr/local/lib/python3.9/site-packages/gunicorn/app/wsgiapp.py", line 58, in load
    return self.load_wsgiapp()
  File "/usr/local/lib/python3.9/site-packages/gunicorn/app/wsgiapp.py", line 48, in load_wsgiapp
    return util.import_app(self.app_uri)
  File "/usr/local/lib/python3.9/site-packages/gunicorn/util.py", line 359, in import_app
    mod = importlib.import_module(module)
  File "/usr/local/lib/python3.9/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 680, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/opt/services/djangoapp/src/project/project/wsgi.py", line 16, in <module>
    application = get_wsgi_application()
  File "/usr/local/lib/python3.9/site-packages/django/core/wsgi.py", line 12, in get_wsgi_application
    django.setup(set_prefix=False)
  File "/usr/local/lib/python3.9/site-packages/django/__init__.py", line 24, in setup
    apps.populate(settings.INSTALLED_APPS)
  File "/usr/local/lib/python3.9/site-packages/django/apps/registry.py", line 91, in populate
    app_config = AppConfig.create(entry)
  File "/usr/local/lib/python3.9/site-packages/django/apps/config.py", line 228, in create
    import_module(entry)
  File "/usr/local/lib/python3.9/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 984, in _find_and_load_unlocked
ModuleNotFoundError: No module named 'activity'
[2022-07-11 16:57:34 +0000] [14] [INFO] Worker exiting (pid: 14)
[2022-07-11 16:57:34 +0000] [13] [INFO] Shutting down: Master
[2022-07-11 16:57:34 +0000] [13] [INFO] Reason: Worker failed to boot.
[2022-07-11 16:57:37 +0000] [15] [INFO] Starting gunicorn 20.1.0
[2022-07-11 16:57:37 +0000] [15] [INFO] Listening at: http://0.0.0.0:8001 (15)
[2022-07-11 16:57:37 +0000] [15] [INFO] Using worker: sync
[2022-07-11 16:57:37 +0000] [16] [INFO] Booting worker with pid: 16
[2022-07-11 16:57:37 +0000] [16] [ERROR] Exception in worker process
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/gunicorn/arbiter.py", line 589, in spawn_worker
    worker.init_process()
  File "/usr/local/lib/python3.9/site-packages/gunicorn/workers/base.py", line 134, in init_process
    self.load_wsgi()
  File "/usr/local/lib/python3.9/site-packages/gunicorn/workers/base.py", line 146, in load_wsgi
    self.wsgi = self.app.wsgi()
  File "/usr/local/lib/python3.9/site-packages/gunicorn/app/base.py", line 67, in wsgi
    self.callable = self.load()
  File "/usr/local/lib/python3.9/site-packages/gunicorn/app/wsgiapp.py", line 58, in load
    return self.load_wsgiapp()
  File "/usr/local/lib/python3.9/site-packages/gunicorn/app/wsgiapp.py", line 48, in load_wsgiapp
    return util.import_app(self.app_uri)
  File "/usr/local/lib/python3.9/site-packages/gunicorn/util.py", line 359, in import_app
    mod = importlib.import_module(module)
  File "/usr/local/lib/python3.9/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 680, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/opt/services/djangoapp/src/project/project/wsgi.py", line 16, in <module>
    application = get_wsgi_application()
  File "/usr/local/lib/python3.9/site-packages/django/core/wsgi.py", line 12, in get_wsgi_application
    django.setup(set_prefix=False)
  File "/usr/local/lib/python3.9/site-packages/django/__init__.py", line 24, in setup
    apps.populate(settings.INSTALLED_APPS)
  File "/usr/local/lib/python3.9/site-packages/django/apps/registry.py", line 91, in populate
    app_config = AppConfig.create(entry)
  File "/usr/local/lib/python3.9/site-packages/django/apps/config.py", line 228, in create
    import_module(entry)
  File "/usr/local/lib/python3.9/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 984, in _find_and_load_unlocked
ModuleNotFoundError: No module named 'activity'
[2022-07-11 16:57:37 +0000] [16] [INFO] Worker exiting (pid: 16)
[2022-07-11 16:57:37 +0000] [15] [INFO] Shutting down: Master
[2022-07-11 16:57:37 +0000] [15] [INFO] Reason: Worker failed to boot.
[2022-07-11 17:03:23 +0000] [9] [INFO] Starting gunicorn 20.1.0
[2022-07-11 17:03:23 +0000] [9] [INFO] Listening at: http://0.0.0.0:8001 (9)
[2022-07-11 17:03:23 +0000] [9] [INFO] Using worker: sync
[2022-07-11 17:03:23 +0000] [10] [INFO] Booting worker with pid: 10
[2022-07-11 17:03:23 +0000] [10] [ERROR] Exception in worker process
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/gunicorn/arbiter.py", line 589, in spawn_worker
    worker.init_process()
  File "/usr/local/lib/python3.9/site-packages/gunicorn/workers/base.py", line 134, in init_process
    self.load_wsgi()
  File "/usr/local/lib/python3.9/site-packages/gunicorn/workers/base.py", line 146, in load_wsgi
    self.wsgi = self.app.wsgi()
  File "/usr/local/lib/python3.9/site-packages/gunicorn/app/base.py", line 67, in wsgi
    self.callable = self.load()
  File "/usr/local/lib/python3.9/site-packages/gunicorn/app/wsgiapp.py", line 58, in load
    return self.load_wsgiapp()
  File "/usr/local/lib/python3.9/site-packages/gunicorn/app/wsgiapp.py", line 48, in load_wsgiapp
    return util.import_app(self.app_uri)
  File "/usr/local/lib/python3.9/site-packages/gunicorn/util.py", line 359, in import_app
    mod = importlib.import_module(module)
  File "/usr/local/lib/python3.9/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 680, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/opt/services/djangoapp/src/project/project/wsgi.py", line 16, in <module>
    application = get_wsgi_application()
  File "/usr/local/lib/python3.9/site-packages/django/core/wsgi.py", line 12, in get_wsgi_application
    django.setup(set_prefix=False)
  File "/usr/local/lib/python3.9/site-packages/django/__init__.py", line 24, in setup
    apps.populate(settings.INSTALLED_APPS)
  File "/usr/local/lib/python3.9/site-packages/django/apps/registry.py", line 91, in populate
    app_config = AppConfig.create(entry)
  File "/usr/local/lib/python3.9/site-packages/django/apps/config.py", line 228, in create
    import_module(entry)
  File "/usr/local/lib/python3.9/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 984, in _find_and_load_unlocked
ModuleNotFoundError: No module named 'activity'
[2022-07-11 17:03:23 +0000] [10] [INFO] Worker exiting (pid: 10)
[2022-07-11 17:03:23 +0000] [9] [INFO] Shutting down: Master
[2022-07-11 17:03:23 +0000] [9] [INFO] Reason: Worker failed to boot.
[2022-07-11 17:03:24 +0000] [11] [INFO] Starting gunicorn 20.1.0
[2022-07-11 17:03:24 +0000] [11] [INFO] Listening at: http://0.0.0.0:8001 (11)
[2022-07-11 17:03:24 +0000] [11] [INFO] Using worker: sync
[2022-07-11 17:03:24 +0000] [12] [INFO] Booting worker with pid: 12
[2022-07-11 17:03:24 +0000] [12] [ERROR] Exception in worker process
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/gunicorn/arbiter.py", line 589, in spawn_worker
    worker.init_process()
  File "/usr/local/lib/python3.9/site-packages/gunicorn/workers/base.py", line 134, in init_process
    self.load_wsgi()
  File "/usr/local/lib/python3.9/site-packages/gunicorn/workers/base.py", line 146, in load_wsgi
    self.wsgi = self.app.wsgi()
  File "/usr/local/lib/python3.9/site-packages/gunicorn/app/base.py", line 67, in wsgi
    self.callable = self.load()
  File "/usr/local/lib/python3.9/site-packages/gunicorn/app/wsgiapp.py", line 58, in load
    return self.load_wsgiapp()
  File "/usr/local/lib/python3.9/site-packages/gunicorn/app/wsgiapp.py", line 48, in load_wsgiapp
    return util.import_app(self.app_uri)
  File "/usr/local/lib/python3.9/site-packages/gunicorn/util.py", line 359, in import_app
    mod = importlib.import_module(module)
  File "/usr/local/lib/python3.9/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 680, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/opt/services/djangoapp/src/project/project/wsgi.py", line 16, in <module>
    application = get_wsgi_application()
  File "/usr/local/lib/python3.9/site-packages/django/core/wsgi.py", line 12, in get_wsgi_application
    django.setup(set_prefix=False)
  File "/usr/local/lib/python3.9/site-packages/django/__init__.py", line 24, in setup
    apps.populate(settings.INSTALLED_APPS)
  File "/usr/local/lib/python3.9/site-packages/django/apps/registry.py", line 91, in populate
    app_config = AppConfig.create(entry)
  File "/usr/local/lib/python3.9/site-packages/django/apps/config.py", line 228, in create
    import_module(entry)
  File "/usr/local/lib/python3.9/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 984, in _find_and_load_unlocked
ModuleNotFoundError: No module named 'activity'
[2022-07-11 17:03:24 +0000] [12] [INFO] Worker exiting (pid: 12)
[2022-07-11 17:03:24 +0000] [11] [INFO] Shutting down: Master
[2022-07-11 17:03:24 +0000] [11] [INFO] Reason: Worker failed to boot.
[2022-07-11 17:03:26 +0000] [13] [INFO] Starting gunicorn 20.1.0
[2022-07-11 17:03:26 +0000] [13] [INFO] Listening at: http://0.0.0.0:8001 (13)
[2022-07-11 17:03:26 +0000] [13] [INFO] Using worker: sync
[2022-07-11 17:03:26 +0000] [14] [INFO] Booting worker with pid: 14
[2022-07-11 17:03:26 +0000] [14] [ERROR] Exception in worker process
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/gunicorn/arbiter.py", line 589, in spawn_worker
    worker.init_process()
  File "/usr/local/lib/python3.9/site-packages/gunicorn/workers/base.py", line 134, in init_process
    self.load_wsgi()
  File "/usr/local/lib/python3.9/site-packages/gunicorn/workers/base.py", line 146, in load_wsgi
    self.wsgi = self.app.wsgi()
  File "/usr/local/lib/python3.9/site-packages/gunicorn/app/base.py", line 67, in wsgi
    self.callable = self.load()
  File "/usr/local/lib/python3.9/site-packages/gunicorn/app/wsgiapp.py", line 58, in load
    return self.load_wsgiapp()
  File "/usr/local/lib/python3.9/site-packages/gunicorn/app/wsgiapp.py", line 48, in load_wsgiapp
    return util.import_app(self.app_uri)
  File "/usr/local/lib/python3.9/site-packages/gunicorn/util.py", line 359, in import_app
    mod = importlib.import_module(module)
  File "/usr/local/lib/python3.9/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 680, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/opt/services/djangoapp/src/project/project/wsgi.py", line 16, in <module>
    application = get_wsgi_application()
  File "/usr/local/lib/python3.9/site-packages/django/core/wsgi.py", line 12, in get_wsgi_application
    django.setup(set_prefix=False)
  File "/usr/local/lib/python3.9/site-packages/django/__init__.py", line 24, in setup
    apps.populate(settings.INSTALLED_APPS)
  File "/usr/local/lib/python3.9/site-packages/django/apps/registry.py", line 91, in populate
    app_config = AppConfig.create(entry)
  File "/usr/local/lib/python3.9/site-packages/django/apps/config.py", line 228, in create
    import_module(entry)
  File "/usr/local/lib/python3.9/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 984, in _find_and_load_unlocked
ModuleNotFoundError: No module named 'activity'
[2022-07-11 17:03:26 +0000] [14] [INFO] Worker exiting (pid: 14)
[2022-07-11 17:03:26 +0000] [13] [INFO] Shutting down: Master
[2022-07-11 17:03:26 +0000] [13] [INFO] Reason: Worker failed to boot.
[2022-07-11 17:03:29 +0000] [15] [INFO] Starting gunicorn 20.1.0
[2022-07-11 17:03:29 +0000] [15] [INFO] Listening at: http://0.0.0.0:8001 (15)
[2022-07-11 17:03:29 +0000] [15] [INFO] Using worker: sync
[2022-07-11 17:03:29 +0000] [16] [INFO] Booting worker with pid: 16
[2022-07-11 17:03:30 +0000] [16] [ERROR] Exception in worker process
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/gunicorn/arbiter.py", line 589, in spawn_worker
    worker.init_process()
  File "/usr/local/lib/python3.9/site-packages/gunicorn/workers/base.py", line 134, in init_process
    self.load_wsgi()
  File "/usr/local/lib/python3.9/site-packages/gunicorn/workers/base.py", line 146, in load_wsgi
    self.wsgi = self.app.wsgi()
  File "/usr/local/lib/python3.9/site-packages/gunicorn/app/base.py", line 67, in wsgi
    self.callable = self.load()
  File "/usr/local/lib/python3.9/site-packages/gunicorn/app/wsgiapp.py", line 58, in load
    return self.load_wsgiapp()
  File "/usr/local/lib/python3.9/site-packages/gunicorn/app/wsgiapp.py", line 48, in load_wsgiapp
    return util.import_app(self.app_uri)
  File "/usr/local/lib/python3.9/site-packages/gunicorn/util.py", line 359, in import_app
    mod = importlib.import_module(module)
  File "/usr/local/lib/python3.9/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 680, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/opt/services/djangoapp/src/project/project/wsgi.py", line 16, in <module>
    application = get_wsgi_application()
  File "/usr/local/lib/python3.9/site-packages/django/core/wsgi.py", line 12, in get_wsgi_application
    django.setup(set_prefix=False)
  File "/usr/local/lib/python3.9/site-packages/django/__init__.py", line 24, in setup
    apps.populate(settings.INSTALLED_APPS)
  File "/usr/local/lib/python3.9/site-packages/django/apps/registry.py", line 91, in populate
    app_config = AppConfig.create(entry)
  File "/usr/local/lib/python3.9/site-packages/django/apps/config.py", line 228, in create
    import_module(entry)
  File "/usr/local/lib/python3.9/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 984, in _find_and_load_unlocked
ModuleNotFoundError: No module named 'activity'
[2022-07-11 17:03:30 +0000] [16] [INFO] Worker exiting (pid: 16)
[2022-07-11 17:03:30 +0000] [15] [INFO] Shutting down: Master
[2022-07-11 17:03:30 +0000] [15] [INFO] Reason: Worker failed to boot.
[2022-07-11 17:05:34 +0000] [10] [INFO] Starting gunicorn 20.1.0
[2022-07-11 17:05:34 +0000] [10] [INFO] Listening at: http://0.0.0.0:8001 (10)
[2022-07-11 17:05:34 +0000] [10] [INFO] Using worker: sync
[2022-07-11 17:05:34 +0000] [11] [INFO] Booting worker with pid: 11
[2022-07-11 17:05:39 +0000] [10] [INFO] Handling signal: term
[2022-07-11 17:05:39 +0000] [11] [INFO] Worker exiting (pid: 11)
[2022-07-11 17:05:39 +0000] [10] [INFO] Shutting down: Master
[2022-07-11 17:14:52 +0000] [8] [INFO] Starting gunicorn 20.1.0
[2022-07-11 17:14:52 +0000] [8] [INFO] Listening at: http://0.0.0.0:8001 (8)
[2022-07-11 17:14:52 +0000] [8] [INFO] Using worker: sync
[2022-07-11 17:14:52 +0000] [9] [INFO] Booting worker with pid: 9
[2022-07-11 17:14:59 +0000] [8] [INFO] Handling signal: term
[2022-07-11 17:14:59 +0000] [9] [INFO] Worker exiting (pid: 9)
[2022-07-11 17:14:59 +0000] [8] [INFO] Shutting down: Master
[2022-07-11 17:17:28 +0000] [9] [INFO] Starting gunicorn 20.1.0
[2022-07-11 17:17:28 +0000] [9] [INFO] Listening at: http://0.0.0.0:8001 (9)
[2022-07-11 17:17:28 +0000] [9] [INFO] Using worker: sync
[2022-07-11 17:17:28 +0000] [10] [INFO] Booting worker with pid: 10
[2022-07-11 17:17:38 +0000] [9] [INFO] Handling signal: term
[2022-07-11 17:17:38 +0000] [10] [INFO] Worker exiting (pid: 10)
[2022-07-11 17:17:38 +0000] [9] [INFO] Shutting down: Master
[2022-07-11 17:22:13 +0000] [8] [INFO] Starting gunicorn 20.1.0
[2022-07-11 17:22:13 +0000] [8] [INFO] Listening at: http://0.0.0.0:8001 (8)
[2022-07-11 17:22:13 +0000] [8] [INFO] Using worker: sync
[2022-07-11 17:22:13 +0000] [9] [INFO] Booting worker with pid: 9
[2022-07-11 17:22:20 +0000] [8] [INFO] Handling signal: term
[2022-07-11 17:22:20 +0000] [9] [INFO] Worker exiting (pid: 9)
[2022-07-11 17:22:20 +0000] [8] [INFO] Shutting down: Master
[2022-07-11 17:33:58 +0000] [8] [INFO] Starting gunicorn 20.1.0
[2022-07-11 17:33:58 +0000] [8] [INFO] Listening at: http://0.0.0.0:8001 (8)
[2022-07-11 17:33:58 +0000] [8] [INFO] Using worker: sync
[2022-07-11 17:33:58 +0000] [9] [INFO] Booting worker with pid: 9
[2022-07-11 17:37:54 +0000] [8] [INFO] Handling signal: term
[2022-07-11 17:37:54 +0000] [9] [INFO] Worker exiting (pid: 9)
[2022-07-11 17:37:55 +0000] [8] [INFO] Shutting down: Master
[2022-07-12 08:18:15 +0000] [7] [INFO] Starting gunicorn 20.1.0
[2022-07-12 08:18:15 +0000] [7] [INFO] Listening at: http://0.0.0.0:8001 (7)
[2022-07-12 08:18:15 +0000] [7] [INFO] Using worker: sync
[2022-07-12 08:18:15 +0000] [8] [INFO] Booting worker with pid: 8
[2022-07-12 08:31:47 +0000] [7] [INFO] Handling signal: term
[2022-07-12 08:31:47 +0000] [8] [INFO] Worker exiting (pid: 8)
[2022-07-12 08:31:47 +0000] [7] [INFO] Shutting down: Master
[2022-07-14 07:57:42 +0000] [7] [INFO] Starting gunicorn 20.1.0
[2022-07-14 07:57:42 +0000] [7] [INFO] Listening at: http://0.0.0.0:8001 (7)
[2022-07-14 07:57:42 +0000] [7] [INFO] Using worker: sync
[2022-07-14 07:57:42 +0000] [8] [INFO] Booting worker with pid: 8
[2022-07-14 08:48:02 +0000] [7] [CRITICAL] WORKER TIMEOUT (pid:8)
[2022-07-14 08:48:02 +0000] [8] [INFO] Worker exiting (pid: 8)
[2022-07-14 08:48:02 +0000] [25] [INFO] Booting worker with pid: 25
[2022-07-14 08:48:49 +0000] [7] [CRITICAL] WORKER TIMEOUT (pid:25)
[2022-07-14 08:48:49 +0000] [25] [INFO] Worker exiting (pid: 25)
[2022-07-14 08:48:49 +0000] [28] [INFO] Booting worker with pid: 28
[2022-07-14 08:49:23 +0000] [7] [INFO] Handling signal: term
[2022-07-14 08:49:23 +0000] [28] [INFO] Worker exiting (pid: 28)
[2022-07-14 08:49:23 +0000] [7] [INFO] Shutting down: Master
[2022-07-14 10:20:14 +0000] [9] [INFO] Starting gunicorn 20.1.0
[2022-07-14 10:20:14 +0000] [9] [INFO] Listening at: http://0.0.0.0:8001 (9)
[2022-07-14 10:20:14 +0000] [9] [INFO] Using worker: sync
[2022-07-14 10:20:14 +0000] [10] [INFO] Booting worker with pid: 10
[2022-07-14 10:21:27 +0000] [9] [INFO] Handling signal: term
[2022-07-14 10:21:27 +0000] [10] [INFO] Worker exiting (pid: 10)
[2022-07-14 10:21:27 +0000] [9] [INFO] Shutting down: Master
[2022-07-14 10:26:53 +0000] [8] [INFO] Starting gunicorn 20.1.0
[2022-07-14 10:26:53 +0000] [8] [INFO] Listening at: http://0.0.0.0:8001 (8)
[2022-07-14 10:26:53 +0000] [8] [INFO] Using worker: sync
[2022-07-14 10:26:53 +0000] [9] [INFO] Booting worker with pid: 9
[2022-07-14 10:26:57 +0000] [8] [INFO] Handling signal: term
[2022-07-14 10:26:57 +0000] [9] [INFO] Worker exiting (pid: 9)
[2022-07-14 10:26:57 +0000] [8] [INFO] Shutting down: Master
